spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ranidu-harshana/MICROSERVICE
          search-paths:
            - 'configuration-store/*service'
          # username: ranidu-harshana
          # password: ranidu-harshana
